import type { CommandCenterAdapter } from './commandCenterAdapter'
import { normalizeCommandCenterSnapshot } from './normalizeCommandCenterSnapshot'
import type { CommandCenterSnapshot } from '../shared/types'

const snapshot: CommandCenterSnapshot = {
  generatedAt: '2026-05-13T13:15:00Z',
  agents: [
    {
      id: 'agent-krab',
      name: 'Краб 🦀',
      role: 'main/orchestrator',
      status: 'working',
      currentTaskId: 'task-command-center-step-6',
      summary: 'Тримає послідовність маленьких кроків і контролює read-only MVP scope.',
      lastSeen: '2026-05-13T13:16:00Z',
    },
    {
      id: 'agent-dev',
      name: 'Дев 🛠️',
      role: 'coding',
      status: 'working',
      currentTaskId: 'task-visual-polish',
      summary: 'Вносить layout polish і готує зміни до build/lint verification.',
      lastSeen: '2026-05-13T13:14:00Z',
    },
    {
      id: 'agent-bastion',
      name: 'Бастіон ⚙️',
      role: 'ops',
      status: 'waiting',
      summary: 'Очікує QA сигнал перед release/deploy контуром.',
      lastSeen: '2026-05-13T13:08:00Z',
    },
    {
      id: 'agent-shturman',
      name: 'Штурман 🔎',
      role: 'research',
      status: 'idle',
      summary: 'Тримає backlog notes для наступних продуктових рішень.',
      lastSeen: '2026-05-13T12:58:00Z',
    },
    {
      id: 'agent-spec',
      name: 'Спек 📐',
      role: 'requirements',
      status: 'done',
      summary: 'Зафіксував MVP як mock-first read-only dashboard.',
      lastSeen: '2026-05-13T13:02:00Z',
    },
    {
      id: 'agent-varta',
      name: 'Варта 🛡️',
      role: 'QA',
      status: 'blocked',
      currentTaskId: 'task-lint-build',
      summary: 'Готова перевіряти gates, але чекає актуальний build artifact.',
      lastSeen: '2026-05-13T13:15:00Z',
      blockerReason: 'Немає свіжого результату build/lint після останніх UI змін.',
    },
    {
      id: 'agent-rezhyser',
      name: 'Режисер 🎬',
      role: 'video',
      status: 'idle',
      summary: 'Video workflows залишені поза поточним MVP.',
      lastSeen: '2026-05-13T12:45:00Z',
    },
    {
      id: 'agent-verstalnyk',
      name: 'Верстальник 🎨',
      role: 'UI/layout',
      status: 'done',
      summary: 'Підготував graphite/gold layout основу для dashboard.',
      lastSeen: '2026-05-13T13:06:00Z',
    },
    {
      id: 'agent-desk',
      name: 'Деск 💹',
      role: 'trading',
      status: 'error',
      summary: 'Trading сектор видимий на карті, але real feed вимкнений у MVP.',
      lastSeen: '2026-05-13T13:11:00Z',
      blockerReason: 'Real market feed не підключений; показуємо тільки mock safety state.',
    },
  ],
  tasks: [
    {
      id: 'task-command-center-step-6',
      title: 'Крок 6: visual QA',
      status: 'in_progress',
      ownerAgentId: 'agent-krab',
      priority: 'high',
      dependency: 'UI polish',
      nextStep: 'Перевірити timeline',
    },
    {
      id: 'task-visual-polish',
      title: 'Polish першого екрану',
      status: 'delegated',
      ownerAgentId: 'agent-dev',
      priority: 'high',
      dependency: 'Step 9 layout',
      nextStep: 'Відкрити Graph',
    },
    {
      id: 'task-lint-build',
      title: 'Перевірити lint і build',
      status: 'queued',
      ownerAgentId: 'agent-varta',
      priority: 'medium',
      dependency: 'Свіжий build artifact',
      nextStep: 'Очікує input',
      blockerReason: 'QA не має нового build/lint результату для перевірки.',
    },
    {
      id: 'task-ops-readiness',
      title: 'Ops readiness check',
      status: 'waiting',
      ownerAgentId: 'agent-bastion',
      priority: 'medium',
      dependency: 'QA gates',
      nextStep: 'Очікує input',
    },
    {
      id: 'task-research-notes',
      title: 'Research backlog notes',
      status: 'queued',
      ownerAgentId: 'agent-shturman',
      priority: 'medium',
      nextStep: 'Перевірити timeline',
    },
    {
      id: 'task-spec-mvp',
      title: 'MVP statuses погоджено',
      status: 'completed',
      ownerAgentId: 'agent-spec',
      priority: 'high',
      nextStep: 'Відкрити Graph',
    },
    {
      id: 'task-trading-feed',
      title: 'Trading feed disabled for MVP',
      status: 'failed',
      ownerAgentId: 'agent-desk',
      priority: 'low',
      dependency: 'Market data connector',
      nextStep: 'Очікує input',
      blockerReason: 'Trading feed intentionally disabled until real data source is approved.',
    },
    {
      id: 'task-video-later',
      title: 'Video workflows later',
      status: 'blocked',
      ownerAgentId: 'agent-rezhyser',
      priority: 'low',
      dependency: 'Media scope decision',
      nextStep: 'Перевірити timeline',
      blockerReason: 'Video workflows відкладені до окремого продуктового кроку.',
    },
  ],
  activity: [
    {
      id: 'event-001',
      timestamp: '2026-05-13T13:04:00Z',
      agentId: 'agent-krab',
      category: 'system',
      severity: 'info',
      summary: 'MVP scope зафіксовано на read-only mock data.',
    },
    {
      id: 'event-002',
      timestamp: '2026-05-13T13:10:00Z',
      agentId: 'agent-dev',
      category: 'task',
      severity: 'success',
      summary: 'Dashboard polish виконується без real OpenClaw data.',
    },
    {
      id: 'event-003',
      timestamp: '2026-05-13T13:15:00Z',
      agentId: 'agent-varta',
      category: 'blocker',
      severity: 'warning',
      summary: 'QA gates: build, lint, diff check перед push.',
    },
    {
      id: 'event-004',
      timestamp: '2026-05-13T13:11:00Z',
      agentId: 'agent-desk',
      category: 'blocker',
      severity: 'critical',
      summary: 'Trading feed лишається disabled; сектор показує mock error state.',
    },
    {
      id: 'event-005',
      timestamp: '2026-05-13T13:08:00Z',
      agentId: 'agent-bastion',
      category: 'deploy',
      severity: 'warning',
      summary: 'Deploy readiness чекає QA gate без live керування.',
    },
    {
      id: 'event-006',
      timestamp: '2026-05-13T13:06:00Z',
      agentId: 'agent-verstalnyk',
      category: 'agent',
      severity: 'success',
      summary: 'Graphite panels і gold highlights прийняті як базова тема.',
    },
    {
      id: 'event-007',
      timestamp: '2026-05-13T13:03:00Z',
      agentId: 'agent-krab',
      category: 'system',
      severity: 'info',
      summary: 'Room/Graph toggle лишається read-only navigation surface.',
    },
    {
      id: 'event-008',
      timestamp: '2026-05-13T12:59:00Z',
      agentId: 'agent-krab',
      category: 'system',
      severity: 'info',
      summary: 'Live control actions disabled until real OpenClaw data contract exists.',
    },
  ],
  workflow: {
    nodes: [
      {
        id: 'workflow-krab',
        agentId: 'agent-krab',
        label: 'Краб',
        lane: 'Оркестрація',
        x: 50,
        y: 12,
      },
      {
        id: 'workflow-spec',
        agentId: 'agent-spec',
        label: 'Спек',
        lane: 'Вимоги',
        x: 18,
        y: 36,
      },
      {
        id: 'workflow-dev',
        agentId: 'agent-dev',
        label: 'Дев',
        lane: 'Код',
        x: 50,
        y: 36,
      },
      {
        id: 'workflow-verstalnyk',
        agentId: 'agent-verstalnyk',
        label: 'Верстальник',
        lane: 'UI',
        x: 82,
        y: 36,
      },
      {
        id: 'workflow-varta',
        agentId: 'agent-varta',
        label: 'Варта',
        lane: 'QA',
        x: 50,
        y: 58,
      },
      {
        id: 'workflow-rezhyser',
        agentId: 'agent-rezhyser',
        label: 'Режисер',
        lane: 'Media',
        x: 18,
        y: 68,
      },
      {
        id: 'workflow-bastion',
        agentId: 'agent-bastion',
        label: 'Бастіон',
        lane: 'Deploy',
        x: 34,
        y: 84,
      },
      {
        id: 'workflow-shturman',
        agentId: 'agent-shturman',
        label: 'Штурман',
        lane: 'Backlog',
        x: 66,
        y: 84,
      },
      {
        id: 'workflow-desk',
        agentId: 'agent-desk',
        label: 'Деск',
        lane: 'Market',
        x: 82,
        y: 68,
      },
    ],
    edges: [
      {
        id: 'edge-krab-spec',
        from: 'workflow-krab',
        to: 'workflow-spec',
        label: 'scope',
      },
      {
        id: 'edge-krab-dev',
        from: 'workflow-krab',
        to: 'workflow-dev',
        label: 'task',
      },
      {
        id: 'edge-krab-verstalnyk',
        from: 'workflow-krab',
        to: 'workflow-verstalnyk',
        label: 'layout',
      },
      {
        id: 'edge-spec-dev',
        from: 'workflow-spec',
        to: 'workflow-dev',
        label: 'criteria',
      },
      {
        id: 'edge-dev-varta',
        from: 'workflow-dev',
        to: 'workflow-varta',
        label: 'verify',
      },
      {
        id: 'edge-verstalnyk-varta',
        from: 'workflow-verstalnyk',
        to: 'workflow-varta',
        label: 'visual QA',
      },
      {
        id: 'edge-varta-bastion',
        from: 'workflow-varta',
        to: 'workflow-bastion',
        label: 'release',
      },
      {
        id: 'edge-varta-shturman',
        from: 'workflow-varta',
        to: 'workflow-shturman',
        label: 'notes',
      },
      {
        id: 'edge-shturman-rezhyser',
        from: 'workflow-shturman',
        to: 'workflow-rezhyser',
        label: 'media',
      },
      {
        id: 'edge-shturman-desk',
        from: 'workflow-shturman',
        to: 'workflow-desk',
        label: 'signals',
      },
      {
        id: 'edge-krab-desk',
        from: 'workflow-krab',
        to: 'workflow-desk',
        label: 'watch',
      },
    ],
  },
}

export const mockCommandCenterAdapter: CommandCenterAdapter = {
  source: 'mock',
  getSnapshot() {
    return normalizeCommandCenterSnapshot(snapshot)
  },
}
